---- 관련된 Procedure 및 Function들을 Package로 묶는다.--as는 추가

---PACKAGE 생성(HEADER)---------



CREATE OR REPLACE PACKAGE emp_mgmt as
    PROCEDURE ADJUST_SAL(V_FLAG VARCHAR2, V_EMPNO NUMBER, V_PCT NUMBER) ;
    FUNCTION GET_ANNUAL_SAL(V_EMPNO NUMBER) RETURN NUMBER;
     FUNCTION GET_RETIRE_MONEY(V_EMPNO NUMBER) RETURN NUMBER;
     PROCEDURE REMOVE_EMP (V_EMPNO NUMBER);
     FUNCTION GET_HIREDATE (V_EMPNO NUMBER, V_FMT VARCHAR2 ) RETURN VARCHAR2;
END emp_mgmt;
