--*case03*--
SELECT EMPNO
     , ENAME
     , COMM
     , CASE     WHEN COMM IS NULL THEN '해당사항 없음'
                WHEN COMM=0 THEN '수당없음'
                WHEN COMM>0 THEN '수당: '||COMM
                END "COMM_TEXT"
  FROM EMP;
---------
--*3장-X1*--
SELECT NAME
     , HEIGHT
     , RANK() OVER(ORDER BY HEIGHT DESC) AS "RANK"
     , DENSE_RANK() OVER(ORDER BY HEIGHT DESC) AS "RANK2"
     , ROW_NUMBER() OVER(ORDER BY HEIGHT DESC) AS "RANK3"
  FROM STUDENT
 WHERE HEIGHT>=170;
---------
--*3장-X2*--
SELECT NAME
     , GRADE
     , WEIGHT
     , RANK() OVER(PARTITION BY GRADE ORDER BY WEIGHT DESC) AS"RANK"
  FROM STUDENT;
---------
--*3장-X3*--
SELECT NAME
     , JUMIN
     , DEPTNO1
     , DECODE(SUBSTR(JUMIN,7,1),1,'M','F') AS "MF"
     , WEIGHT
     , SUM(WEIGHT) OVER(PARTITION BY DEPTNO1,SUBSTR(JUMIN,7,1) ORDER BY WEIGHT DESC) AS "TOTAL"
  FROM STUDENT;
---------
--*3장-Y1*--

--쓰다가 만 코드....망
--SELECT DISTINCT SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) AS "DOMAIN"
--, COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)) OVER(PARTITION BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) ORDER BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) ) AS "EA"
--, COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)) OVER() AS "SUM_DOMAIN"
--, RATIO_TO_REPORT(COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))) OVER()*100
--  FROM PROFESSOR
--  GROUP BY EMAIL;

SELECT SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) AS "DOMAIN"
     , COUNT(*) AS "EA"
     , SUM(COUNT(*)) OVER() AS "SUM_DOMAIN"
     , COUNT(*)/SUM(COUNT(*)) OVER() * 100 "%"
  FROM PROFESSOR
 GROUP BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
 ORDER BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1);
 
--SELECT SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) AS "DOMAIN"
--     , COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)) AS "EA"
--     , SUM(COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))) OVER() AS "SUM_DOMAIN"
--     , COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))/SUM(COUNT(SUBSTR(EMAIL,INSTR(EMAIL,'@')+1))) OVER() * 100 "%"
--  FROM PROFESSOR
-- GROUP BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1)
-- ORDER BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1);
---------
--*3장-Y2*--

--쓰다 만 코드........
--SELECT NAME
--     , TEL
--     , TO_CHAR(PAY,'999,999,999') AS "PAY"
----     , SUBSTR(TEL,1,INSTR(TEL,')')-1)
----     , SUBSTR(TEL,INSTR(TEL,')')+1,INSTR(TEL,'-')-INSTR(TEL,')')-1)
--     , SUM(PAY) OVER(PARTITION BY SUBSTR(TEL,1,INSTR(TEL,')')-1)) AS "TOTAL_AREA"
--     , ROUND(PAY/SUM(PAY) OVER(PARTITION BY SUBSTR(TEL,1,INSTR(TEL,')')-1)) * 100,2) "RATIO%"
--  FROM EMP2;

SELECT NAME
     , TEL
     , TO_CHAR(PAY,'999,999,999') AS "PAY"
     , TO_CHAR(SUM(PAY) OVER(PARTITION BY 
        SUBSTR(TEL,1,INSTR(TEL,')')-1)),'999,999,999') AS "TOTAL_AREA"
     , ROUND(RATIO_TO_REPORT(SUM(PAY)) OVER(PARTITION BY 
        SUBSTR(TEL,1,INSTR(TEL,')')-1)) * 100,2) "RATIO(%)"
--        ,   ROUND(RATIO_TO_REPORT(SUM(PAY)) OVER(PARTITION BY 
--        substr(name,1,'Kevin')) * 100,2) "RATIO(%)"
--        ,SUBSTR(TEL,1,INSTR(TEL,')')-1) D
--        ,SUBSTR(TEL,1,INSTR(TEL,')')-1)) * 100,2) D
  FROM EMP2
 GROUP BY NAME, TEL, PAY;
 
---------
