--복습
SELECT * FROM professor;
SELECT * FROM EMP;
SELECT * FROM STUDENT;
SELECT * FROM FRUIT;
SELECT * FROM MEMBER;
SELECT * FROM CUSTOMER;

ROLLBACK;
COMMIT;
------------------------
SELECT * FROM PROFESSOR3;
DESC PROFESSOR3;
SELECT * FROM PROFESSOR4;

------------4장-A8 본인----------------

INSERT INTO T_MINUS(NO1, NO2, NO3) VALUES(1,1,1);

ALTER TABLE PROFESSOR2
MODIFY(HIREDATE DATE);

ALTER TABLE PROFESSOR2
MODIFY(BONUS NUMBER(5));

------------4장-A7 본인--DROP---------------
ALTER TABLE PROFESSOR3
DROP COLUMN CHECK_CARD_YN;

SELECT * FROM PROFESSOR3;
DESC PROFESSOR3;
SELECT * FROM PROFESSOR4;

------------4장-A6 본인- ㅡMODIFY---------------
ALTER TABLE PROFESSOR3
MODIFY(EMAIL VARCHAR(100));


SELECT * FROM PROFESSOR3;
DESC PROFESSOR3;
SELECT * FROM PROFESSOR4;

------------4장-A5 본인----------------
--ALTER TABLE 테이블 명
--RENAME 컬럼 컬럼이름 TO 컬럼이름바꿀거

ALTER TABLE PROFESSOR3
RENAME COLUMN CARD_YN TO CHECK_CARD_YN;


------------4장-A4 본인----------------
CREATE TABLE PROFESSOR4
AS
SELECT *  FROM PROFESSOR3
--거짓을 걸어서 테이블 생성
WHERE 1=2;

SELECT * FROM PROFESSOR4;
------------4장-A3 본인----------------

SELECT * FROM PROFESSOR3;


ALTER TABLE PROFESSOR3
ADD (CARD_YN VARCHAR2(10) DEFAULT 'N');
--ADD (CARD_YN CHAR(1) DEFAULT 'N');


------------4장-A2 본인----------------
SELECT * FROM PROFESSOR3;

CREATE TABLE PROFESSOR3
AS
SELECT PROFNO, NAME , EMAIL FROM PROFESSOR;

ALTER TABLE DEPT7
DROP COLUMN LOCATION;

------------4장-A1 강사님----------------
DESC PROFESSOR;
DESC PROFESSOR2;

SELECT * FROM PROFESSOR2;

CREATE TABLE PROFESSOR2
( PROFNO NUMBER(8)
,NAME VARCHAR2(30)  
,ID VARCHAR2(20)  
,POSITION VARCHAR2(50)  
,PAY NUMBER(5)   
,HIREDATE DATE 
,BONUS NUMBER(5)   
,DEPTNO NUMBER(3)   
,EMAIL VARCHAR2(100) 
,HPAGE VARCHAR2(100) 
);
-----------------본인
ALTER TABLE PROFESSOR2
MODIFY(HIREDATE DATE);

ALTER TABLE PROFESSOR2
MODIFY(HPAGE VARCHAR(100));

ALTER TABLE PROFESSOR2
MODIFY(BONUS NUMBER(5));

CREATE TABLE PROFESSOR2
AS
SELECT * FROM PROFESSOR;

------------CASE-2 본인----------------

SELECT GNAME
,POINT
, CASE                                WHEN  POINT BETWEEN 1 AND 99999 THEN 'C'
                                         WHEN  POINT BETWEEN 100000 AND 299999 THEN 'B '
                                         WHEN  POINT BETWEEN 300000 AND 600000 THEN 'A '
                                         WHEN  POINT > 600000 THEN 'S'
                                         
                                                                                                         END "CLASS" 
FROM CUSTOMER
ORDER BY POINT DESC;
-- 숫자 넣을때 콤마 사용 X 오류난다아ㅏ

------------DECODE-3 강사님----------------
-- (INSTR(EMAIL,'@') = 8일때로
--INSTAR 부분 숫자로 7,6,4 집어넣음
-------
--INSTR '.',1,2 - INSTR'.'1,1 = 4일때
--'.',1,1+1 이 3,5 일때 DECODE

------------DECODE-3 본인----------------
SELECT EMAIL
,DECODE(INSTR(EMAIL,'@')-1,7
,(REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'???????'))
,(DECODE(INSTR(EMAIL,'@')-1,6
,(REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'??????'))
,(REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'????'))
))) "EMAIL_?"
,HPAGE
,DECODE((INSTR(HPAGE,'.')-INSTR(HPAGE,'/')),5
,(REPLACE(HPAGE,SUBSTR(HPAGE,8,3),'***'))
,(REPLACE(HPAGE,SUBSTR(HPAGE,8,4),'*****'))
)  "HPAGE_*"

FROM PROFESSOR
WHERE HPAGE IS NOT NULL;





--SELECT EMAIL
--,DECODE(INSTR(EMAIL,'@')-1,7
--,(REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1,7),'???????'),0)
----뜯어보니까 문제점이 나온다.
--,DECODE(INSTR(EMAIL,'@')-1,7
--,(REPLACE(EMAIL,SUBSTR(EMAIL,1,7,7),'???????'),0)
--,SUBSTR(HPAGE,8,3)
--,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1)
--,INSTR(EMAIL,'@')-1 
--,INSTR(EMAIL,'@') 
--,REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'?') 
--FROM PROFESSOR
--WHERE HPAGE IS NOT NULL;




------------_REPLACE-3 강사님----------------


SELECT NAME
--,RPAD(JUMIN,8,SUBSTR('*******',8)) R
--,LPAD(JUMIN,8) L
--,INSTR(JUMIN,7)
,WEIGHT
,JUMIN
--,REPLACE(JUMIN,INSTR(JUMIN,7),'*')SECURE
--가운데 있는걸 바꾸게.
,REPLACE(JUMIN,SUBSTR(JUMIN,7,7),'*******')SECURE
FROM STUDENT;


------------_SUBSTR,INSTR-3 강사님----------------
SELECT NAME
,HPAGE
,SUBSTR(HPAGE,INSTR(HPAGE,'/')+2,(INSTR(HPAGE,'.')-2)-(INSTR(HPAGE,'/'))) WWW
,INSTR(HPAGE,'/')+2
FROM PROFESSOR
WHERE HPAGE IS NOT NULL;


------------_SUBSTR,INSTR-3----------------
SELECT NAME
,HPAGE
--,INSTR(HPAGE,'.') P
--,INSTR(HPAGE,'/',1,2) P
,SUBSTR(HPAGE,INSTR(HPAGE,'/',1,2)+1,INSTR(HPAGE,'.')-INSTR(HPAGE,'/',1,2)-1) WWW
FROM PROFESSOR
WHERE HPAGE IS NOT NULL;


-------------INSTR-3-강사님---------------

SELECT NAME
,POSITION
,INSTR(POSITION,'p') P
,EMAIL
FROM PROFESSOR
WHERE EMAIL LIKE '%net';

-------------INSTR-3----------------

SELECT NAME
,POSITION
,INSTR(POSITION,'p') P
--,INSTR(EMAIL,'.') P
,EMAIL
,DECODE(SUBSTR(EMAIL, INSTR(EMAIL,'.')+1),'net',0) P
FROM PROFESSOR
WHERE DECODE(SUBSTR(EMAIL, INSTR(EMAIL,'.')+1),'net',0) = 0;

-------------SUBSTR-3----------------
SELECT NAME
,SUBSTR(JUMIN,3,2) MONTH
--,AN_KEY_DAP(NAME,'Ni%')
,AN_KEY_DAP
--, DECODE(NAME,)
FROM MEMBER
WHERE AN_KEY_DAP LIKE 'Ni%';

----------
SELECT *
FROM MEMBER;


-------------3-A14 강사님----------------
SELECT DEPTNO
,NAME
,PAY
,SUM(PAY) OVER( PARTITION BY DEPTNO  ) "TOTAL _DEPTNO"
,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( PARTITION BY DEPTNO ))*100, 2) "RATIO %"

FROM PROFESSOR
GROUP BY DEPTNO, NAME,PAY
--ORDER BY는 왜 쓴거지
ORDER BY 1;

-------------3-A14---------------
--형식이 같다
SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER( PARTITION BY DEPTNO) SUM_DEPT
,ROUND((RATIO_TO_REPORT (SUM(SAL)) OVER (PARTITION BY DEPTNO  ))*100, 2) "%"
FROM EMP
GROUP BY DEPTNO,ENAME,SAL;


SELECT DEPTNO
,NAME
,PAY
,SUM(PAY) OVER( PARTITION BY DEPTNO  ) "TOTAL _DEPTNO"
--,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( ))*100, 2) "RATIO %"
,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( PARTITION BY DEPTNO ))*100, 2) "RATIO %"

FROM PROFESSOR
GROUP BY DEPTNO, NAME,PAY
--ORDER BY는 왜 쓴거지
ORDER BY 5 DESC;




-------------3-A13-강사님-----------------
SELECT DEPTNO
,NAME
,PAY
,SUM(PAY) "TOTAL PAY"
--,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( ))*100, 2) "RATIO %"
,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( ))*100, 2) "RATIO %"

FROM PROFESSOR
GROUP BY DEPTNO, NAME,PAY
--ORDER BY는 왜 쓴거지
ORDER BY 5 DESC;

-------------3-A13-------------------
--RATIO 는 GROUP BY랑 같이 써야한다 
--컬럼 전부 그룹화 시켜야 적용이 가능
-- ㅜㅜ
SELECT DEPTNO
,NAME
,PAY
,SUM(PAY) "TOTAL PAY"
--,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( ))*100, 2) "RATIO %"
,ROUND((RATIO_TO_REPORT (SUM(PAY)) OVER ( ))*100, 2) "RATIO %"

FROM PROFESSOR
GROUP BY DEPTNO, NAME,PAY;



-----------3-A11-강사님-------------------
SELECT L_CODE "대출 종목코드"
,L_STORE "대출 지점"
,L_DATE "대출일자"
, L_QTY "대출건수"
, L_TOTAL "대출총액"
, SUM(L_TOTAL) OVER(PARTITION BY L_CODE, L_STORE ORDER BY L_DATE) "누적대출금액"
 FROM LOAN;

-----------3-A11--------------------
--문제를 좀 읽자고
SELECT L_CODE "대출 종목코드"
,L_STORE "대출 지점"
,L_DATE "대출일자"
, L_QTY "대출건수"
, L_TOTAL "대출총액"
, SUM(L_TOTAL) OVER(PARTITION BY L_CODE, L_STORE ORDER BY L_TOTAL) "누적대출금액"
 FROM LOAN;

-----------3-A10--------------------
--SELECT * FROM LOAN;

SELECT L_DATE "대출일자"
, L_CODE "대출 종목코드"
, L_QTY "대출건수"
, L_TOTAL "대출총액"
, SUM(L_TOTAL) OVER(ORDER BY L_TOTAL) "누적대출금액"
 FROM LOAN
 WHERE L_STORE = 1000;
 
SELECT SUM(DECODE(NAME,'apple',PRICE))  "APPLE"
,SUM(DECODE(NAME,'grape',PRICE))  "GRAPE"
,SUM(DECODE(NAME,'orange',PRICE)) "ORANGE"
FROM FRUIT;

-----------3-A9-강사님-------------------
--PARTITION BY 왜 안먹지..?

SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER( PARTITION BY DEPTNO) SUM_DEPT
,ROUND((RATIO_TO_REPORT (SUM(SAL)) OVER (PARTITION BY DEPTNO  ))*100, 2) "%"
FROM EMP
GROUP BY DEPTNO,ENAME,SAL;
-----------3-A9--------------------
SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER( ORDER BY DEPTNO) SUM_DEPT
--,SUM(SAL) OVER( ORDER BY DEPTNO) SUM_DEPT
,ROUND((RATIO_TO_REPORT (SUM(SAL)) OVER (  ))*100, 2) "AAA"
--,ROUND((RATIO_TO_REPORT (SUM(SAL)) OVER (  ))*100, 2) "AAA"
-- 비율 정렬이 필요 
-- SUM 누적 합 이 왜이래
--,ROUND(SAL /SUM(SAL) OVER ( ORDER BY SAL )*100,2)  "%"
FROM EMP
GROUP BY DEPTNO,ENAME,SAL
;

-----------3-A8-강사님-------------------
--??????? 밖으로 빼오니까 된다..?
SELECT DEPTNO 
,ENAME
,TOTAL
,AAA "%"
FROM(
SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER() TOTAL
,ROUND((RATIO_TO_REPORT (SUM(SAL)) OVER (  ))*100, 2) "AAA"
--,ROUND(SAL /SUM(SAL) OVER ( ORDER BY SAL )*100,2)  "%"
FROM EMP
GROUP BY DEPTNO,ENAME,SAL
ORDER BY 5 DESC
)
;


SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER() TOTAL_SAL
,ROUND((RATIO_TO_REPORT (SUM(SAL)) OVER (  ))*100, 2) "%"
--,ROUND(SAL /SUM(SAL) OVER ( ORDER BY SAL )*100,2)  "%"
FROM EMP
GROUP BY DEPTNO,ENAME,SAL
ORDER BY 5 DESC;


-----------3-A8---------------------
--문제좀 읽자

--SELECT DEPTNO
--,ENAME
--,SUM(SAL) TOTAL_SAL
----,RATIO_TO_REPORT (SUM(SAL)) OVER ( ORDER BY SAL ))*100)||'%' "%"
----,ROUND((SAL /SUM(SAL)) OVER ( ORDER BY SAL ))*100,2) ||'%' "%"
--FROM EMP;






-----------3-A7---------------------
--PARTITION
SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) "TOTAL"
FROM EMP;



-----------3-A6---강사님------------------


SELECT 
COUNT(NAME) || 'EA' || '(' || (COUNT(*) / count(*))*100 || '%)' "TOTAL"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'02','SEOUL'))  || 'EA (' ||
COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'02','SEOUL')) /COUNT(NAME)*100 || '%)' "SEOUL"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'031','GYEONGGI'))  || 'EA (' ||
COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'031','GYEONGGI')) /COUNT(NAME)*100 || '%)' "GYEONGGI"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'051','BUSAN'))  || 'EA (' ||
COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'051','BUSAN')) /COUNT(NAME)*100 || '%)' "BUSAN"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'052','ULSAN'))  || 'EA (' ||
COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'052','ULSAN')) /COUNT(NAME)*100 || '%)' "ULSAN"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'053','DAEGUE'))  || 'EA (' ||
COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'053','DAEGUE')) /COUNT(NAME)*100 || '%)' "DAEGUE"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'055','GYEONGNAM'))  || 'EA (' ||
COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')',1,1)-1),'055','GYEONGNAM')) /COUNT(NAME)*100 || '%)' "GYEONGNAM"


FROM STUDENT;
-----------3-A6---------------------
SELECT 
COUNT(*) || 'EA' || '(' || (COUNT(*) / count(*))*100 || '%)' "TOTAL"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0)) 
 || 'EA' || '(' || round((count(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0)))*100 / COUNT(*) ,0) || '%)' "SEOUL"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',0)) 
 || 'EA' || '(' || round((count(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',0)))*100 / COUNT(*) ,0) || '%)'"GYEONGGI"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',0)) 
 || 'EA' || '(' || round((count(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',0)))*100 / COUNT(*) ,0) || '%)'"BUSAN"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',0)) 
 || 'EA' || '(' || round((count(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',0)))*100 / COUNT(*) ,0) || '%)'"ULSAN"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',0))  
 || 'EA' || '(' || round((count(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',0)))*100 / COUNT(*) ,0) || '%)'"DAEGUE"

,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',0)) 
 || 'EA' || '(' || round((count(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',0)))*100 / COUNT(*) ,0) || '%)'"GYEONGNAM"
FROM STUDENT;



-----------3-A5-강사님-----------------

--대소문자 구분!!!!!!

SELECT SUM(DECODE(NAME,'apple',PRICE))  "APPLE"
,SUM(DECODE(NAME,'grape',PRICE))  "GRAPE"
,SUM(DECODE(NAME,'orange',PRICE)) "ORANGE"

FROM FRUIT;


SELECT SUM(DECODE(NAME,'apple',100))  "APPLE"
,SUM(DECODE(NAME,'grape',200))  "GRAPE"
,SUM(DECODE(NAME,'orange',300)) "ORANGE"

FROM FRUIT;

SELECT MAX(DECODE(NAME,'apple',100))  "APPLE"
,MAX(DECODE(NAME,'grape',200))  "GRAPE"
,MAX(DECODE(NAME,'orange',300)) "ORANGE"

FROM FRUIT;

SELECT MIN(DECODE(NAME,'apple',100))  "APPLE"
,MIN(DECODE(NAME,'grape',200))  "GRAPE"
,MIN(DECODE(NAME,'orange',300)) "ORANGE"

FROM FRUIT;




SELECT DECODE(NAME,'apple',100)  "APPLE"
,DECODE(NAME,'grape',200)  "GRAPE"
,DECODE(NAME,'ORANGE',300)  "ORANGE"

FROM FRUIT;

-----------3-A5---------------------

SELECT 
MIN(PRICE) "APPLE"
,AVG(PRICE) "GRAPE"
,MAX(PRICE) "ORANGE"
FROM FRUIT;



-----------3-A4----------------------
SELECT DEPTNO
,ENAME
,SAL
,SUM(SAL) OVER(ORDER BY SAL) "TOTAL"
FROM EMP;

-----------3-A3---강사님-------------------

SELECT 
COUNT(*)  "TOTAL"
,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0)) "SEOUL"
--DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',0) "SEOUL"
,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',0))  "GYEONGGI"
,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',0))  "BUSAN"
,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',0))  "ULSAN"
,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',0))  "DAEGUE"
,COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',0))  "GYEONGNAM"
FROM STUDENT;

-----------3-A3----------------------
SELECT TEL
,SUBSTR(TEL,1,INSTR(TEL,')')-1)
FROM STUDENT;

--SELECT COUNT(*)  "TOTAL"
--,COUNT(DECODE(TO_CHAR(TEL,SUBSTR(TEL,1,INSTR(TEL,')')-1),02,0)) "SEOUL"
--,COUNT(DECODE(TO_CHAR(TEL,'MM'),'031',031))  "GYEONGGI"
--,COUNT(DECODE(TO_CHAR(TEL,'MM'),'051',051))  "BUSAN"
--,COUNT(DECODE(TO_CHAR(TEL,'MM'),'052',052))  "ULSAN"
--,COUNT(DECODE(TO_CHAR(TEL,'MM'),'053',053))  "DAEGUE"
--,COUNT(DECODE(TO_CHAR(TEL,'MM'),'055',055))  "GYEONGNAM"
--FROM STUDENT;

-----------3-A2--강사님---------------------
--TOCHAR사용해서 빠르게 뽑아옴
-- COUNT가 핵심인듯

SELECT COUNT(*) || 'EA' "TOTAL"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'01',1)) || 'EA' "JAN"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'02',1)) || 'EA' "FEB"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'03',1)) || 'EA' "MAR"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'04',1)) || 'EA' "APR"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'05',1)) || 'EA' "MAY"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'06',1)) || 'EA' "JUN"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'07',1)) || 'EA' "JUL"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'08',1)) || 'EA' "AUG"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'09',1)) || 'EA' "SEP"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'10',1)) || 'EA' "OCT"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'11',1)) || 'EA' "NOV"
,COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'12',1)) || 'EA' "DEC"

FROM STUDENT;




-----------3-A2-----------------------

SELECT * FROM STUDENT;

SELECT BIRTHDAY
FROM STUDENT;

SELECT SUM(BIRTHDAY) OVER (ORDER BY P_TOTAL ) TOTAL
                ,DECODE(DAY,'MON',BIRTHDAY) JAN
                ,DECODE(DAY,'TUE',BIRTHDAY) FEB
                ,DECODE(DAY,'WED',BIRTHDAY) MAR
                ,DECODE(DAY,'THU',BIRTHDAY) APR
                ,DECODE(DAY,'FRI',BIRTHDAY) MAY
                ,DECODE(DAY,'SAT',BIRTHDAY) JUN
                ,DECODE(DAY,'SAT',BIRTHDAY) JUL
                ,DECODE(DAY,'SAT',BIRTHDAY) AUG
                ,DECODE(DAY,'SAT',BIRTHDAY) SEP
                ,DECODE(DAY,'SAT',BIRTHDAY) OCT
                ,DECODE(DAY,'SAT',BIRTHDAY) NOV
                ,DECODE(DAY,'SAT',BIRTHDAY) DEC
                FROM STUDENT;


-----------3-A1-----------------------
--왜 구문오류
--컬럼이름이 안써진다. ,,?
--SELECT 
--MAX(SAL+(NVL(COMM,0))
--,MIN(SAL+(NVL(COMM,0))
--,ROUND(AVG(SAL + NVL(COMM,0)),1) 
----FROM EMP;