--LAG LEAD RANK 수업후 이후 문제
SELECT *
FROM PANMAE;
------------3장 9번 강사님
------------3장 9번 




------------3장 9번 강사님
SELECT P_CODE
,P_STORE
,P_QTY
,SUM(P_QTY) OVER ( ) "TOTAL_QTY"
,ROUND((RATIO_TO_REPORT (SUM(P_QTY)) OVER ( ))*100,2)||'%' "QTY%"
FROM PANMAE
WHERE P_CODE = 100
GROUP BY P_CODE, P_STORE, P_QTY;
------------3장 9번 
------------3장 9번 
SELECT P_CODE
,P_STORE
,P_QTY
,SUM(P_QTY) OVER (  ) "TOTAL_QTY"
,ROUND(P_QTY /SUM(P_QTY) OVER ( ORDER BY P_CODE )*100,2)||'%' "QTY%"
FROM PANMAE
WHERE P_CODE = 100
GROUP BY P_CODE,P_STORE,P_QTY; 
--GROUP BY 쓰면 위에있는 컬럼으로만 제약걸림


------------3장 8번 강사님
------------3장 8번 
SELECT P_CODE
,P_STORE
,P_DATE
,P_QTY
,P_TOTAL
,SUM(P_TOTAL) OVER (PARTITION BY P_CODE ,P_STORE  ORDER BY P_DATE   ) "TOTAL"
FROM PANMAE;

------------3장 7번 강사님
SELECT P_DATE
,P_CODE
,P_QTY
,P_TOTAL
,SUM(P_TOTAL) OVER (PARTITION BY P_CODE ORDER BY P_TOTAL   ) "TOTAL"

FROM PANMAE
WHERE P_STORE = '1000' ;

------------3장 7번 시도 랭크
--SELECT 안 SELECT
SELECT P_CODE
,P_QTY
,P_TOTAL
,P_DATE

 (SELECT P_TOTAL
,RANK () OVER(ORDER BY P_TOTAL)
FROM PANMAE
WHERE P_STORE = '1000' 

)
FROM PANMAE;

------------3장 6번 강사님

SELECT P_DATE
,P_CODE
,P_QTY
,P_TOTAL
,SUM(P_TOTAL) OVER (ORDER BY P_TOTAL ) "TOTAL"

FROM PANMAE
WHERE P_STORE = '1000' ;

------------3장 6번
SELECT P_DATE
,P_CODE
,P_QTY
,P_TOTAL
--,SUM() OVER ( P_TOTAL) TOTAL
,SUM(P_TOTAL) OVER ( ) "TOTAL"
--,SUM(P_TOTAL) OVER (RANK() OVER(ORDER BY P_TOTAL) ) TOTAL
FROM PANMAE
WHERE P_STORE = '1000' ;


------------3장 5번 강사님
SELECT EMPNO
,ENAME
,SAL
,DEPTNO
,JOB
,RANK() OVER (PARTITION BY DEPTNO,JOB  ORDER BY SAL )   "RANK"
FROM EMP;
------------3장 5번
SELECT EMPNO
,ENAME
,SAL
,DEPTNO
,JOB
,ROW_NUMBER() OVER (PARTITION BY JOB  ORDER BY DEPTNO )   "RANK"
,DENSE_RANK() OVER (PARTITION BY JOB  ORDER BY DEPTNO )   "RANK"
,RANK() OVER (PARTITION BY JOB  ORDER BY DEPTNO )   "RANK"
,RANK() OVER (ORDER BY DEPTNO )   "RANK"
,RANK() OVER (PARTITION BY JOB  ORDER BY DEPTNO DESC )   "RANK"
FROM EMP
--SAL 왜 안넣고 계산중..?
ORDER BY DEPTNO;





------------3장 4번
SELECT EMPNO
,ENAME
,SAL
,DEPTNO
,RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC)   "RANK"
FROM EMP;


SELECT EMPNO
,ENAME
,SAL
,DEPTNO
--,RANK() OVER (PARTITION BY DEPTNO = '10') "RANK"
--,RANK() OVER (ORDER BY SAL) "RANK" PARTITION BY DEPTNO='10'
--,RANK() OVER (PARTITION BY DEPTNO = 10 , ((ORDER BY SAL)))
FROM EMP;
--GROUP BY DEPTNO;
