SELECT * FROM professor;
SELECT * FROM EMP;
SELECT * FROM STUDENT;
----AVG-1-2번 강사님
----AVG-1 -2번





----AVG-1-2번 강사님
SELECT POSITION
,ROUND(AVG(PAY),2) "AVG"
FROM PROFESSOR
GROUP BY POSITION 
HAVING AVG(PAY) >= 300 ;
----AVG-1 -2번
SELECT POSITION
,ROUND(AVG(NVL(PAY,0),2) 
FROM PROFESSOR
GROUP BY POSITION HAVING PAY >= 300 ;


----SUM-1-1 -2번 강사님
----SUM-1-1 -2번
SELECT SUM(PAY) SUM
--,COUNT (PAY) 
,AVG(PAY) A
,AVG(NVL(PAY,0)) A
,MAX(PAY) X
,MIN(PAY) N
,ROUND(STDDEV(PAY),2) S 
,ROUND(VARIANCE(PAY),2) S

FROM PROFESSOR;


----CASE-1 -2번 시도
SELECT NAME
,PAY
, CASE              WHEN  PAY BETWEEN 1 AND 300 THEN 'GRADE 1'
                         WHEN  PAY BETWEEN 301 AND 400 THEN 'GRADE 2'
                         WHEN  PAY BETWEEN '401' AND '500' THEN 'GRADE 3'
                         WHEN  PAY > '500' THEN 'GRADE 4'
              
                        END "GRADE" 
FROM PROFESSOR

ORDER BY PAY DESC;

----CASE-1 -2번
SELECT NAME
,PAY
, CASE              WHEN  PAY BETWEEN 1 AND 300 THEN 'GRADE 1'
                         WHEN  PAY BETWEEN 301 AND 400 THEN 'GRADE 2'
                         WHEN  PAY BETWEEN '401' AND '500' THEN 'GRADE 3'
                         WHEN  PAY > '500' THEN 'GRADE 4'
              
                        END "GRADE" 
FROM PROFESSOR
ORDER BY PAY DESC;


----_DECODE -2번 강사님
--또 뭐가 오타가 났나보다.. ? 고치고 옮겨적기
SELECT NAME
,HPAGE
,DECODE((INSTR(HPAGE,'.')-INSTR(HPAGE,'/')),5
 ,(REPLACE(HPAGE,SUBSTR(HPAGE,8,3),'study'))
,(REPLACE(HPAGE,SUBSTR(HPAGE,8,4),'study'))
 )  STUDY_HPAGE

FROM PROFESSOR
WHERE HPAGE IS NOT NULL;


----_DECODE -2번
SELECT NAME
,HPAGE
,REPLACE(HPAGE,SUBSTR(HPAGE,INSTR(HPAGE,'.',1,1)-3,3),'study') STUDY_HPAGE
--,INSTR(HPAGE,'.',1,1) S
--,SUBSTR(HPAGE,INSTR(HPAGE,'.',1,1)-3,3) S
--,SUBSTR(HPAGE,INSTR(HPAGE,'.',1,1)-3,INSTR(HPAGE,'.',1,1)-INSTR(HPAGE,'/')) S
--,SUBSTR(HPAGE,(INSTR(HPAGE,'.',1,1))-(INSTR(HPAGE,'/'))) S
FROM PROFESSOR
WHERE HPAGE IS NOT NULL;

----형변환02 -2번 강사님
----형변환02 -2번
SELECT ENAME
,SAL
,COMM
,TO_CHAR((SAL*12),'$99,999')  "Y_SAL"
,TO_CHAR(((SAL*12)+COMM),'$99,999') "TOTAL"
, TO_CHAR(((SAL*12)+COMM)*1.05,'$99,999') "5%UP"
, TO_CHAR(((SAL*12)+COMM)*0.95,'$99,999') "5%DOWN"
FROM EMP
WHERE COMM IS NOT NULL;
--계산 0.95

----REPLACE-2번 강사님
----REPLACE-2번
SELECT ENAME
,JOB
--,REPLACE(JOB,A,'?') "JOB?"
  ,REPLACE (JOB,SUBSTR(JOB,3,1),'?') 
--    ,REPLACE (JOB,'A','?') 
FROM EMP
WHERE DEPTNO = 20;

----SUBSTR / INSTR -2번 강사님
SELECT NAME
,TEL
,SUBSTR(TEL,INSTR(TEL, ')')+1,(INSTR(TEL, '-')-1)-(INSTR(TEL, ')'))) GUK_NO
FROM STUDENT
WHERE DEPTNO1 = 101;
----SUBSTR / INSTR -2번
SELECT NAME
,TEL
,SUBSTR(TEL,INSTR(TEL, ')')+1,3) GUK_NO
,INSTR(TEL, ')')
FROM STUDENT
WHERE DEPTNO1 = 101;

----INSTR-2 IN+INSTR번 강사님
SELECT NAME
,GRADE
,TEL
,INSTR(TEL,'6') "6"
FROM STUDENT
WHERE GRADE IN ('2','4');
--작은따옴표
----INSTR-2 IN+INSTR 번
SELECT NAME
,GRADE
,TEL
,INSTR(TEL,6,1) "6"
FROM STUDENT
WHERE GRADE IN (2,4);


---SUBSTR -2번 강사님
----SUBSTR -2번
SELECT NAME
,HEIGHT
,SUBSTR(JUMIN ,5,2) DAY
FROM STUDENT
WHERE HEIGHT >= 180;


----2C-6번 강사님
----2C-6번
SELECT NAME
,PAY
,BONUS
FROM PROFESSOR
WHERE (PAY >= 300 AND BONUS IS NULL) OR  (PAY >= 500) ;
--괄호 쳐줘서 순서

----2C-5번 강사님
SELECT PROFNO
,NAME
,PAY
,BONUS
,PAY*12+BONUS TOTAL
,DEPTNO
FROM PROFESSOR
WHERE BONUS IS NOT NULL
ORDER BY PROFNO DESC ,PAY*12+BONUS;
----2C-5번
--SELECT PROFNO
--,NAME
--,PAY
--,BONUS
--,PAY*12+BONUS TOTAL
--FROM PROFESSOR
--ORDER BY PROFNO DESC AND TOTAL ASC;


----2C-4번 강사님
----2C-4번
SELECT NAME
,ID
,POSITION
FROM PROFESSOR
WHERE ID LIKE '%er';



----2C-3번 강사님
----2C-3번
SELECT NAME
,PAY
,HIREDATE
FROM PROFESSOR
WHERE PAY >= 300 AND PAY <= 500;


----2C-2번 강사님
----2C-2번
SELECT NAME
,ID
,HPAGE
FROM PROFESSOR
WHERE DEPTNO = 102 AND HPAGE IS NOT NULL;
--작성한 DEPTNO 삭제했던,,,?

----2C-1번 강사님
----2C-1번
SELECT NAME
,PAY
,BONUS
FROM PROFESSOR
WHERE BONUS > 80
ORDER BY PAY DESC;



SELECT * FROM professor;
SELECT * FROM EMP;
SELECT * FROM STUDENT;

