--DECODE 실습

--2-18
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,'COMPUTER ENGINEERING') "DNAME"

FROM PROFESSOR ;

-- 2-19
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,'COMPUTER ENGINEERING','ETC') "DNAME"

FROM PROFESSOR ;

--2-20
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,'COMPUTER ENGINEERING'
,DECODE(DEPTNO , 102 , 'MULTIMEDIA ENGINEERING',(DEPTNO,'SOFTWARE ENGINNERING'))) "DNAME"

FROM PROFESSOR ;

--요게 정답
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,'COMPUTER ENGINEERING'
                            ,102,'MULTIMEDIA ENGINEERING'
                            ,103,'SOFTWARE ENGINNERING'
                            ,'ETC') "DNAME"

FROM PROFESSOR ;


---2-21
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,DECODE(NAME,'Audie Murphy' ,'BEST!')
                            ) "ETC"

FROM PROFESSOR ;

--Audie Murphy 데이터 복사 그대로 클릭하고 CTRL C V 하면 됨

---2-22
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,DECODE(NAME,'Audie Murphy' ,'BEST!','GOOD')
                           ) "ETC"

FROM PROFESSOR ;

----2-23-
SELECT DEPTNO
,NAME
,DECODE(DEPTNO,101,DECODE(NAME,'Audie Murphy' ,'BEST!','GOOD')
                          ,'N/A' ) "ETC"

FROM PROFESSOR ;


----2-24-
SELECT * FROM STUDENT;

SELECT NAME
,JUMIN
,DECODE(SUBSTR(JUMIN,7,1),'1','MAN','2','WOMAN') "GENDER"
--,GENDER
FROM STUDENT
WHERE DEPTNO1 = 101;



